# Generated by Django 4.2.10 on 2024-02-22 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bigmodel',
            name='name',
        ),
        migrations.AlterField(
            model_name='bigmodel',
            name='file',
            field=models.FileField(upload_to='media/'),
        ),
    ]
